<script setup lang="ts">
type Block={id:string;booking_date:string;booking_time:string|null;reason:string|null}
const blocks=ref<Block[]>([]);const date=ref(new Date().toISOString().slice(0,10));const time=ref('');const reason=ref('');const error=ref('');const loading=ref(false)
async function load(){try{blocks.value=(await $fetch<{blockedSlots:Block[]}>('/api/admin/blocked-slots')).blockedSlots}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}}
async function add(){error.value='';loading.value=true;try{await $fetch('/api/admin/blocked-slots',{method:'POST',body:{bookingDate:date.value,bookingTime:time.value||null,reason:reason.value||null}});reason.value='';time.value='';await load()}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Не удалось заблокировать'}finally{loading.value=false}}
async function remove(id:string){if(!confirm('Удалить блокировку?'))return;try{await $fetch(`/api/admin/blocked-slots/${id}`,{method:'DELETE'});await load()}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}}
await load()
</script>
<template><main class="page"><div class="container"><div class="page-head"><div><h1>Blocked time</h1><p>Можно заблокировать весь день или отдельный час</p></div><NuxtLink class="btn" to="/admin">Admin</NuxtLink></div><div class="card form-grid"><label>Дата<input v-model="date" type="date"></label><label>Время<select v-model="time"><option value="">Весь день</option><option v-for="h in 9" :key="h" :value="String(h+8).padStart(2,'0')+':00'">{{String(h+8).padStart(2,'0')}}:00</option></select></label><label>Причина<input v-model="reason" maxlength="200" placeholder="Например: обслуживание"></label><button class="btn primary" :disabled="loading" @click="add">Заблокировать</button></div><div v-if="error" class="error">{{error}}</div><div class="card"><h2>Текущие блокировки</h2><div v-if="!blocks.length">Нет блокировок.</div><div v-for="b in blocks" :key="b.id" class="list-row"><span><strong>{{b.booking_date}}</strong> · {{b.booking_time?String(b.booking_time).slice(0,5):'Весь день'}} · {{b.reason||'Без причины'}}</span><button class="btn danger" @click="remove(b.id)">Удалить</button></div></div></div></main></template>
