<script setup lang="ts">
type User={id:string;name:string;phone:string;banned:boolean;role:string}
type Car={id:string;user_id:string;make:string;model:string;registration_number:string;category:string}
type Booking={id:string;user_id:string;car_id:string;booking_date:string;booking_time:string;status:string;notes:string|null}
const route=useRoute();const bookingId=String(route.query.id||'');const users=ref<User[]>([]);const cars=ref<Car[]>([]);const booking=ref<Booking|null>(null);const error=ref('');const saving=ref(false)
const userCars=computed(()=>cars.value.filter(c=>c.user_id===booking.value?.user_id))
async function load(){try{const [b,u,c]=await Promise.all([$fetch<{bookings:Booking[]}>('/api/admin/bookings'),$fetch<{users:User[]}>('/api/admin/users'),$fetch<{cars:Car[]}>('/api/admin/cars')]);booking.value=b.bookings.find(x=>x.id===bookingId)||null;users.value=u.users;cars.value=c.cars;if(!booking.value)error.value='BOOKING_NOT_FOUND'}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}}
async function save(){if(!booking.value)return;error.value='';saving.value=true;try{await $fetch(`/api/admin/bookings/${bookingId}`,{method:'PATCH',body:{userId:booking.value.user_id,carId:booking.value.car_id,bookingDate:booking.value.booking_date,bookingTime:String(booking.value.booking_time).slice(0,5),status:booking.value.status,notes:booking.value.notes||null}});await navigateTo('/admin/bookings')}catch(e:any){error.value=e?.data?.data?.code||e?.data?.statusMessage||e?.message||'Не удалось сохранить'}finally{saving.value=false}}
await load()
</script>
<template><main class="page"><div class="container"><div class="page-head"><div><h1>Edit booking</h1><p>Изменение бронирования с повторной серверной проверкой</p></div><NuxtLink class="btn" to="/admin/bookings">Назад</NuxtLink></div><div v-if="error" class="error">{{error}}</div><div v-if="booking" class="card form-grid"><label>Клиент<select v-model="booking.user_id"><option v-for="u in users" :key="u.id" :value="u.id">{{u.name}} · {{u.phone}} {{u.banned?'(заблокирован)':''}}</option></select></label><label>Автомобиль<select v-model="booking.car_id"><option v-for="c in userCars" :key="c.id" :value="c.id">{{c.make}} {{c.model}} · {{c.registration_number}}</option></select></label><label>Дата<input v-model="booking.booking_date" type="date"></label><label>Время<select v-model="booking.booking_time"><option v-for="h in 12" :key="h" :value="String(h+8).padStart(2,'0')+':00'">{{String(h+8).padStart(2,'0')}}:00</option></select></label><label>Статус<select v-model="booking.status"><option value="pending">Ожидает</option><option value="confirmed">Подтверждено</option><option value="completed">Завершено</option><option value="cancelled_customer">Отмена клиента</option><option value="cancelled_admin">Отмена админа</option><option value="no_show">Не явился</option></select></label><label>Примечание<textarea v-model="booking.notes" maxlength="1000"></textarea></label><button class="btn primary" :disabled="saving" @click="save">Сохранить</button></div></div></main></template>
