<script setup lang="ts">
type User={id:string;name:string;phone:string;banned:boolean;role:string}
type Car={id:string;user_id:string;make:string;model:string;registration_number:string;category:string}
type Booking={id:string;user_id:string;car_id:string;booking_date:string;booking_time:string;status:string;notes:string|null}
type Slot={time:string;state:string}
const route=useRoute();const bookingId=String(route.query.id||'');const users=ref<User[]>([]);const cars=ref<Car[]>([]);const booking=ref<Booking|null>(null);const slots=ref<Slot[]>([]);const originalSlot=ref('');const error=ref('');const saving=ref(false);const loadingSlots=ref(false)
const activeStatuses=['pending','confirmed']
const isActiveStatus=computed(()=>!!booking.value&&activeStatuses.includes(booking.value.status))
const userCars=computed(()=>cars.value.filter((c:Car)=>c.user_id===booking.value?.user_id))
const selectedSlot=computed(()=>String(booking.value?.booking_time||'').slice(0,5))
const slotLabels:Record<string,string>={available:'Свободно · активно',booked:'Забронировано · активно',blocked:'Заблокировано · неактивно',past:'Прошло · неактивно',holiday:'Праздник · неактивно',outside_booking_window:'Вне окна · неактивно'}
const displaySlots=computed(()=>slots.value.map((s:Slot)=>s.time===originalSlot.value?{...s,state:'current'}:s))
const displaySlotLabels:Record<string,string>={...slotLabels,current:isActiveStatus.value?'Текущее бронирование · активно':'Текущее бронирование · неактивно'}
async function load(){try{const [b,u,c]=await Promise.all([$fetch<{bookings:Booking[]}>('/api/admin/bookings'),$fetch<{users:User[]}>('/api/admin/users'),$fetch<{cars:Car[]}>('/api/admin/cars')]);booking.value=b.bookings.find((x:Booking)=>x.id===bookingId)||null;users.value=u.users;cars.value=c.cars;if(!booking.value)error.value='BOOKING_NOT_FOUND';else{originalSlot.value=String(booking.value.booking_time||'').slice(0,5);await loadSlots()}}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}}
async function loadSlots(){if(!booking.value?.booking_date)return;loadingSlots.value=true;try{slots.value=(await $fetch<{slots:Slot[]}>('/api/availability',{query:{date:booking.value.booking_date}})).slots}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}finally{loadingSlots.value=false}}
watch(()=>booking.value?.user_id,(next:string|undefined,previous:string|undefined)=>{if(booking.value&&previous&&next!==previous)booking.value.car_id=''})
watch(()=>booking.value?.booking_date,async(next:string|undefined,previous:string|undefined)=>{if(next&&next!==previous){booking.value!.booking_time='';await loadSlots()}})
watch(()=>booking.value?.status,async(next:string|undefined,previous:string|undefined)=>{if(next!==previous&&next)await loadSlots()})
function canSelectSlot(s:Slot){if(!booking.value)return false;if(s.time===originalSlot.value&&s.time===selectedSlot.value)return true;if(!isActiveStatus.value)return true;return s.state==='available'}
function selectSlot(s:Slot){if(canSelectSlot(s)&&booking.value)booking.value.booking_time=s.time}
async function save(){if(!booking.value)return;error.value='';if(!booking.value.user_id||!booking.value.car_id){error.value='Выберите клиента и автомобиль';return}if(!userCars.value.some((c:Car)=>c.id===booking.value?.car_id)){error.value='Автомобиль не принадлежит выбранному клиенту';return}if(isActiveStatus.value){const target=slots.value.find((s:Slot)=>s.time===selectedSlot.value);if(!target||target.time!==originalSlot.value&&target.state!=='available'){error.value='Выбранное время недоступно';return}}saving.value=true;try{await $fetch(`/api/admin/bookings/${bookingId}`,{method:'PATCH',body:{userId:booking.value.user_id,carId:booking.value.car_id,bookingDate:booking.value.booking_date,bookingTime:selectedSlot.value,status:booking.value.status,notes:booking.value.notes||null}});await navigateTo('/admin/bookings')}catch(e:any){error.value=e?.data?.data?.code||e?.data?.statusMessage||e?.message||'Не удалось сохранить'}finally{saving.value=false}}
await load()
</script>
<template><main class="page"><div class="container"><div class="page-head"><div><h1>Edit booking</h1><p>Изменение бронирования с повторной серверной проверкой</p></div><NuxtLink class="btn" to="/admin/bookings">Назад</NuxtLink></div><div v-if="error" class="error">{{error}}</div><div v-if="booking" class="card form-grid"><label>Клиент<select v-model="booking.user_id"><option value="">Выберите клиента</option><option v-for="u in users" :key="u.id" :value="u.id">{{u.name}} · {{u.phone}} {{u.banned?'(заблокирован)':''}}</option></select></label><label>Автомобиль<select v-model="booking.car_id" :disabled="!booking.user_id"><option value="">Выберите авто</option><option v-for="c in userCars" :key="c.id" :value="c.id">{{c.make}} {{c.model}} · {{c.registration_number}}</option></select></label><label>Дата<input v-model="booking.booking_date" type="date"></label><label>Статус<select v-model="booking.status"><option value="pending">Ожидает</option><option value="confirmed">Подтверждено</option><option value="completed">Завершено</option><option value="cancelled_customer">Отмена клиента</option><option value="cancelled_admin">Отмена админа</option><option value="no_show">Не явился</option></select></label><label>Примечание<textarea v-model="booking.notes" maxlength="1000"></textarea></label></div><div v-if="booking" class="card"><h2>Время</h2><p v-if="isActiveStatus" class="muted">Показаны все рабочие часы 09:00–20:00. Недоступные часы нельзя выбрать; текущее бронирование остаётся доступным для редактирования.</p><p v-else class="muted">Бронирование неактивно. Можно сохранить историческое время, включая прошедшие или заблокированные часы.</p><div v-if="loadingSlots" class="muted">Загрузка доступности…</div><div v-else class="slot-grid"><button v-for="s in displaySlots" :key="s.time" type="button" class="slot-card" :class="['status-'+s.state,{selected:selectedSlot===s.time}]" :disabled="!canSelectSlot(s)" @click="selectSlot(s)"><strong>{{s.time}}</strong><span>{{displaySlotLabels[s.state]||s.state}}</span></button></div><button class="btn primary" :disabled="saving||!booking.user_id||!booking.car_id||!booking.booking_time" @click="save">Сохранить</button></div></div></main></template>
