<script setup lang="ts">
type Slot={time:string;state:string;available:boolean;reason?:string;bookingId?:string|null}
type Booking={id:string;booking_time:string;status:string;customer_name:string;make:string;model:string;price_cents:number}
function rigaToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Riga',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
const date=ref(rigaToday()); const slots=ref<Slot[]>([]); const bookings=ref<Booking[]>([]); const error=ref(''); const loading=ref(false)
const labels:Record<string,string>={available:'Свободно · активно',booked:'Забронировано · активно',blocked:'Заблокировано · неактивно',past:'Прошло · неактивно',holiday:'Праздник · неактивно',outside_booking_window:'Вне окна · неактивно'}
const statusLabels:Record<string,string>={pending:'Ожидает · активно',confirmed:'Подтверждено · активно',completed:'Завершено · неактивно',cancelled_customer:'Отменено клиентом · неактивно',cancelled_admin:'Отменено админом · неактивно',no_show:'Неявка · неактивно'}
async function load(){loading.value=true;error.value='';try{const [a,b]=await Promise.all([$fetch<{slots:Slot[]}>('/api/availability',{query:{date:date.value}}),$fetch<{bookings:Booking[]}>('/api/admin/bookings',{query:{date:date.value}})]);slots.value=a.slots;bookings.value=b.bookings}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}finally{loading.value=false}}
watch(date,load); await load()
function bookingFor(time:string){return bookings.value.find((b:Booking)=>String(b.booking_time).slice(0,5)===time)}
function cardState(slot:Slot,booking?:Booking){return booking&& !['pending','confirmed'].includes(booking.status) ? 'inactive-booking' : `status-${slot.state}`}
</script>
<template><main class="page"><div class="container"><div class="page-head"><div><h1>Calendar</h1><p>Все 12 рабочих слотов 09:00–20:00. Активные и неактивные отображаются всегда.</p></div><NuxtLink class="btn" to="/admin">Admin</NuxtLink></div><div class="card toolbar"><label>Дата<input v-model="date" type="date"></label></div><div v-if="error" class="error">{{error}}</div><div v-if="loading">Загрузка…</div><div v-else class="slot-grid"><div v-for="slot in slots" :key="slot.time" class="slot-card" :class="cardState(slot,bookingFor(slot.time))"><strong>{{slot.time}}</strong><span>{{bookingFor(slot.time) ? statusLabels[bookingFor(slot.time)!.status] : labels[slot.state]||slot.state}}</span><small v-if="slot.reason">{{slot.reason}}</small><template v-if="bookingFor(slot.time)"><small>{{bookingFor(slot.time)?.customer_name}} · {{bookingFor(slot.time)?.make}} {{bookingFor(slot.time)?.model}}</small><small>{{(bookingFor(slot.time)?.price_cents||0)/100}} €</small><NuxtLink class="btn" :to="`/admin/booking-edit?id=${bookingFor(slot.time)?.id}`">Открыть</NuxtLink></template></div></div></div></main></template>
