<script setup lang="ts">
const route=useRoute();const router=useRouter();const users=ref<any[]>([]);const error=ref('');const loading=ref(true);const activeTab=ref(String(route.query.tab||'all')==='banned'?'banned':'all')
const filteredUsers=computed(()=>activeTab.value==='banned'?users.value.filter((u:any)=>u.role==='customer'&&u.banned):users.value)
const bannedCount=computed(()=>users.value.filter((u:any)=>u.role==='customer'&&u.banned).length)
async function load(){try{users.value=(await $fetch<{users:any[]}>('/api/admin/users')).users}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}finally{loading.value=false}}
function setTab(tab:'all'|'banned'){activeTab.value=tab;router.replace({query:tab==='banned'?{tab:'banned'}:{}})}
async function toggle(u:any){try{const endpoint=u.banned?`/api/admin/users/${u.id}/unban`:`/api/admin/users/${u.id}/ban`;await $fetch(endpoint,{method:'POST',body:u.banned?undefined:{reason:'Администратор заблокировал клиента'}});await load()}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}}
await load()
</script>
<template><main class="page"><div class="container"><div class="page-head"><div><h1>Customers</h1><p>Клиенты, статус блокировки и контакты</p></div><NuxtLink class="btn" to="/admin">Admin</NuxtLink></div><div class="card toolbar"><button class="btn" :class="{primary:activeTab==='all'}" @click="setTab('all')">Все клиенты</button><button class="btn" :class="{primary:activeTab==='banned'}" @click="setTab('banned')">Заблокированные ({{bannedCount}})</button></div><div v-if="error" class="error">{{error}}</div><div v-if="loading">Загрузка…</div><div v-else class="table-wrap"><table><thead><tr><th>Имя</th><th>Email</th><th>Телефон</th><th>Роль</th><th>Статус</th><th></th></tr></thead><tbody><tr v-for="u in filteredUsers" :key="u.id"><td>{{u.name}}</td><td>{{u.email}}</td><td>{{u.phone}}</td><td>{{u.role}}</td><td>{{u.banned?'Заблокирован':'Активен'}}</td><td v-if="u.role==='customer'"><button class="btn" @click="toggle(u)">{{u.banned?'Разблокировать':'Заблокировать'}}</button></td><td v-else>—</td></tr><tr v-if="!filteredUsers.length"><td colspan="6">Нет клиентов в этом разделе.</td></tr></tbody></table></div></div></main></template>
