<script setup lang="ts">
type User={id:string;name:string;email:string;phone:string;banned:boolean};type Car={id:string;user_id:string;make:string;model:string;registration_number:string;category:string};type Slot={time:string;state:string}
const users=ref<User[]>([]);const cars=ref<Car[]>([]);const date=ref(new Date().toISOString().slice(0,10));const userId=ref('');const carId=ref('');const time=ref('');const slots=ref<Slot[]>([]);const error=ref('');const saving=ref(false)
async function load(){try{const [u,c,a]=await Promise.all([$fetch<{users:User[]}>('/api/admin/users'),$fetch<{cars:Car[]}>('/api/admin/cars'),$fetch<{slots:Slot[]}>('/api/availability',{query:{date:date.value}})]);users.value=u.users;cars.value=c.cars;slots.value=a.slots}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}}
watch(date,async()=>{time.value='';try{slots.value=(await $fetch<{slots:Slot[]}>('/api/availability',{query:{date:date.value}})).slots}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Ошибка'}})
const userCars=computed(()=>cars.value.filter(c=>c.user_id===userId.value));watch(userId,()=>{carId.value=''});watch(carId,()=>{if(!slots.value.some(s=>s.time===time.value&&s.state==='available'))time.value=''})
async function save(){error.value='';saving.value=true;try{await $fetch('/api/admin/bookings',{method:'POST',body:{userId:userId.value,carId:carId.value,bookingDate:date.value,bookingTime:time.value}});await load();alert('Бронирование создано')}catch(e:any){error.value=e?.data?.data?.code||e?.data?.statusMessage||e?.message||'Не удалось создать бронирование'}finally{saving.value=false}}
await load()
</script>
<template><main class="page"><div class="container"><div class="page-head"><div><h1>Manual booking</h1><p>Администратор использует тот же booking engine, что и клиент</p></div><NuxtLink class="btn" to="/admin">Admin</NuxtLink></div><div class="card form-grid"><label>Клиент<select v-model="userId"><option value="">Выберите клиента</option><option v-for="u in users.filter(x=>!x.banned)" :key="u.id" :value="u.id">{{u.name}} · {{u.phone}}</option></select></label><label>Автомобиль<select v-model="carId" :disabled="!userId"><option value="">Выберите авто</option><option v-for="c in userCars" :key="c.id" :value="c.id">{{c.make}} {{c.model}} · {{c.registration_number}}</option></select></label><label>Дата<input v-model="date" type="date"></label></div><div class="card"><h2>Время</h2><div class="slot-grid"><button v-for="s in slots" :key="s.time" class="slot-card" :class="['status-'+s.state,{selected:time===s.time}]" :disabled="s.state!=='available'||!carId" @click="time=s.time"><strong>{{s.time}}</strong><span>{{s.state==='available'?'Свободно':s.state}}</span></button></div><button class="btn primary" :disabled="saving||!userId||!carId||!time" @click="save">Создать бронирование</button></div><div v-if="error" class="error">{{error}}</div></div></main></template>
